GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ 
Content-Type: application/json

{
    "title": "First article with NODE.js", 
    "author": "Mariano Pedrini",
    "url": "/api/blogs/2",
    "likes": "15"
}
